Adjust for Maven2: ArtifactResolver
Changed so that it would run against Maven2:
Catch NoSuchMethodError for ArtifactRepository.find(),
which is not available in Maven2, and instead use an
ArtifactResolver to resolve the artifact.